version: '3'

services:
    git:
        image: docker.io/gitea/gitea:1.23.1
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - GITEA__database__DB_TYPE=postgres
            - GITEA__database__HOST=db:5432
            - GITEA__database__NAME=db_name
            - GITEA__database__USER=db_username
            - GITEA__database__PASSWD=db_password
        restart: always
        volumes:
            - data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "80:3000"
            - "2222:2222"
        depends_on:
            - db

    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=db_username
            - POSTGRES_PASSWORD=db_password
            - POSTGRES_DB=db_name
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - postgres-db:/var/lib/postgresql/data

volumes:
    data:
    postgres-db:
